export const servicesList = [
  {
    heading: "SOFT SERVICES:",
    p1: "House Keeping & Janitorial",
    p2: "Pest Control",
    p3: "Garden & Lawn Maintenance",
    p4: "Waste Management",
    p5: "Facade & Glass Cleaning",
    p6: "Deep Cleaning of Factory Sheds",
  },
  {
    heading: "HARD SERVICES:",
    p1: "Electrical & Mechanical Maintenance",
    p2: "HVAC",
    p3: "Water Management & Plumbing",
    p4: "STP / ETP Operations",
    p5: "BMS Operations",
    p6: "3rd Party / Vendor Management",
  },
  {
    heading: "SUPPORT SERVICES:",
    p1: "Staffing – Skilled & Semi skilled",
    p2: "Payroll Management",
    p3: "Mail Room Management",
    p4: "Admin Outsourcing",
  },
  {
    heading: "PRODUCTION SUPPORT / LOGISTICS:",
    p1: "Line operations",
    p2: "Assembly Activities",
    p3: "Material Handling",
    p4: "Date Entry Operators",
    p5: "Welding & Painting",
    p6: "Packaging Loading & Unloading",
  },
  {
    heading: "HOSPITALITY SERVICES:",
    p1: "Guest House Management",
    p2: "Food Court Services",
    p3: "Beverage Vending",
    p4: "Pantry & Cafeteria Services",
  },
  {
    heading: "OTHERS:",
    p1: "Project works",
    p2: "Interiors",
  },
];
